"""Build-time trimming of the Qt payload, shared by both GUI spec files.

Imported from the .spec files, never by the app — nothing here ships.

Both functions are opportunistic: if the thing they want to remove is not in
this platform's wheel, or the toolchain they need is missing, they hand the
binaries back untouched. A build that cannot be slimmed still succeeds.
"""
import os
import re
import subprocess
import sys


# ── ICU ───────────────────────────────────────────────────────────────────────

# Qt's ICU data table is 23.9 MB — 21% of the extracted Linux bundle, and the
# single largest file in it. libQt5Core.so.5 carries a DT_NEEDED entry for it,
# so it cannot simply be dropped, but across every libQt5*.so.5 in the manylinux
# wheel the count of imported ICU symbols is zero: the dependency is recorded,
# the code path is not taken. A stub exporting only the data symbol satisfies
# the loader.
#
# What is actually lost is QTextCodec's table: availableCodecs() falls from 806
# to 2. UTF-8 and UTF-16 are built into Qt and survive, and they are the only
# ones this app uses — it moves text as Python str and QString end to end and
# never asks for a codec by name. Verified by rendering a title mixing Japanese,
# Cyrillic, Arabic, emoji and accented Latin against an unstubbed control: the
# two windows were pixel-identical.
#
# Windows and macOS PyQt5 wheels do not ship ICU at all, so this is a no-op
# there — which is also why the match is on the file, not on sys.platform.

_ICU_DATA = re.compile(r"^libicudata\.so\.(\d+)$")

_STUB_SOURCE = """\
/* Generated by packaging/qt_slim.py — see the note there.
   ICU's data entry point. Nothing in this bundle imports an ICU symbol, so the
   real table is never read; only the DT_NEEDED link has to resolve. */
const char icudt%(ver)s_dat[4] = {0, 0, 0, 0};
"""


def stub_icu_data(binaries, workpath):
    """Swap Qt's ICU data table for a stub that satisfies the dynamic link.

    Returns (binaries, note) — note is a one-line summary for the build log.
    """
    hits = [b for b in binaries if _ICU_DATA.match(os.path.basename(b[0]))]
    if not hits:
        return binaries, "ICU: not bundled on this platform, nothing to do"

    dest, src = hits[0][0], hits[0][1]
    soname = os.path.basename(dest)
    version = _ICU_DATA.match(soname).group(1)

    compiler = os.environ.get("CC") or "cc"
    os.makedirs(workpath, exist_ok=True)
    csrc = os.path.join(workpath, "icu_stub.c")
    stub = os.path.join(workpath, soname)
    with open(csrc, "w", encoding="utf-8") as fh:
        fh.write(_STUB_SOURCE % {"ver": version})

    try:
        subprocess.run(
            [compiler, "-shared", "-fPIC", "-Wl,-soname," + soname,
             "-o", stub, csrc],
            check=True, capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        # No compiler, or it refused: ship the real table rather than a bundle
        # that cannot start. Slimming is an optimisation, not a requirement.
        return binaries, f"ICU: keeping the real table ({compiler} failed: {exc})"

    try:
        saved = os.path.getsize(src) - os.path.getsize(stub)
    except OSError:
        saved = 0

    out = [b for b in binaries if b is not hits[0]]
    out.append((dest, stub, hits[0][2]))
    return out, f"ICU: stubbed {soname}, saving {saved / 1048576:.1f} MB"


# ── Qt plugins ────────────────────────────────────────────────────────────────

# Plugins for ways of running a Qt app that this one has no path to: streaming
# its UI to a browser or a VNC client, painting onto a bare framebuffer or an
# embedded EGL surface, and decoding image formats nothing here reads. The
# thumbnail arrives from YouTube as JPEG or WebP and logo.png is PNG, which Qt
# core decodes itself.
#
# Deliberately kept: xcb and the wayland set are how the window actually opens;
# offscreen is what the test suite renders through; minimal is the fallback when
# neither display server is present; ico and icns are the Windows and macOS
# icon formats.
UNUSED_QT_PLUGINS = (
    "platforms/libqwebgl",
    "platforms/libqlinuxfb",
    "platforms/libqvnc",
    "platforms/libqminimalegl",
    "platforms/libqeglfs",
    "imageformats/libqtiff",
    "imageformats/libqgif",
    "imageformats/libqtga",
    "imageformats/libqwbmp",
)


def drop_unused_qt_plugins(binaries):
    """Returns (binaries, note); a no-op wherever the plugins are not collected."""
    def unwanted(entry):
        path = entry[0].replace("\\", "/")
        return any(p in path for p in UNUSED_QT_PLUGINS)

    dropped = [b for b in binaries if unwanted(b)]
    if not dropped:
        return binaries, "Qt plugins: none of the unused set was collected"

    saved = 0
    for b in dropped:
        try:
            saved += os.path.getsize(b[1])
        except OSError:
            pass
    kept = [b for b in binaries if not unwanted(b)]
    return kept, (f"Qt plugins: dropped {len(dropped)}, "
                  f"saving {saved / 1048576:.1f} MB")


def report(note):
    """Spec files are exec'd with stdout attached to the build log."""
    print(f"[qt_slim] {note}", file=sys.stderr)
